services:
  target:
    image: nginx:alpine
    container_name: target
    ports:
      - "8080:80"

  attacker:
    image: alpine
    # container_name: attacker
    command: >
      sh -c "
        apk add --no-cache curl bash &&
        while true; do
          curl -s http://target:80 > /dev/null
        done
      "
    depends_on:
      - target
