services:
  openldap-ssl:
    image: bitnami/openldap:latest
    container_name: openldap-ssl
    hostname: openldap-ssl
    ports:
      - '1389:1389'
      - '1636:1636'
    environment:
      - LDAP_ROOT=dc=example,dc=org
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=adminpassword
      - LDAP_ENABLE_TLS=yes
      - LDAP_TLS_CERT_FILE=/opt/bitnami/openldap/certs/myserver.crt
      - LDAP_TLS_KEY_FILE=/opt/bitnami/openldap/certs/myserver.key
      - LDAP_TLS_CA_FILE=/opt/bitnami/openldap/certs/myca.crt
    volumes:
      - ./certs/myca.crt:/usr/local/share/ca-certificates/myca.crt
      - ./certs:/opt/bitnami/openldap/certs
    networks:
      openldap-net:


networks:
  openldap-net:
    driver: bridge
