services:
  haproxy:
    image: haproxy:2.9
    container_name: haproxy-l4
    ports:
      - "8080:8080"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    networks:
      - l4_net
    depends_on:
      - backend1
      - backend2
      - backend3

  backend1:
    build: ./web-server
    networks:
      - l4_net

  backend2:
    build: ./web-server
    networks:
      - l4_net

  backend3:
    build: ./web-server
    networks:
      - l4_net


networks:
  l4_net:
    driver: bridge