spring.application.name=million-data-batch

# DB Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/mydb?reWriteBatchedInserts=true
spring.datasource.username=user
spring.datasource.password=password

# Hibernate Performance Tuning
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.batch_size=1000
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.generate_statistics=false