FROM node:20-alpine

# Set the working directory
WORKDIR /app

# Copy everything in the current directory to /app
COPY . .

# Expose the port your Node.js code is listening on
EXPOSE 8080

# Run your script
CMD ["node", "app.js"]
