version: "3.9"

services:
  server:
    image: python:3.12-alpine
    container_name: tcp_server
    networks:
      - tcpnet
    cap_add:
      - NET_ADMIN  # needed for tcpdump
    volumes:
      - ./server.py:/app/server.py
      - ./capture:/capture
    working_dir: /app
    command: >
      sh -c "
      apk add --no-cache tcpdump bash &&
      tcpdump -U -i any tcp port 12345 -w /capture/tcp_flow.pcap &
      python server.py &
      tail -f /dev/null
      "

  client:
    image: python:3.12-alpine
    container_name: tcp_client
    networks:
      - tcpnet
    volumes:
      - ./client.py:/app/client.py
    working_dir: /app
    command: sh -c "python client.py & tail -f /dev/null"

networks:
  tcpnet:
    driver: bridge
