services:
  node1:
    build: .
    container_name: node1
    hostname: node1
    ports:
      - "5001:5000"
    command: ["python", "raft.py", "node1", "node2:5000,node3:5000"]
    networks:
      - raftnet

  node2:
    build: .
    container_name: node2
    hostname: node2
    ports:
      - "5002:5000"
    command: ["python", "raft.py", "node2", "node1:5000,node3:5000"]
    networks:
      - raftnet

  node3:
    build: .
    container_name: node3
    hostname: node3
    ports:
      - "5003:5000"
    command: ["python", "raft.py", "node3", "node1:5000,node2:5000"]
    networks:
      - raftnet

networks:
  raftnet:
    driver: bridge
