services:
  ansible:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ansible 
    tty: true
    stdin_open: true
    command: /bin/bash
    volumes:
      - ./data:/data
    networks:
      - ubuntu-net

networks:
  ubuntu-net:
    driver: bridge

