version: "3.9"

services:
  server:
    image: python:3.11-alpine
    container_name: tcp-server
    working_dir: /app
    volumes:
      - ./server:/app
    command: sh -c "apk add --no-cache tcpdump && python3 server.py"
    networks:
      - keepalive-net
    sysctls:
      net.ipv4.tcp_keepalive_time: 10
      net.ipv4.tcp_keepalive_intvl: 5
      net.ipv4.tcp_keepalive_probes: 3

  client:
    image: python:3.11-alpine
    container_name: tcp-client
    working_dir: /app
    volumes:
      - ./client:/app
    command: sh -c "sleep 3 && python3 client.py"
    networks:
      - keepalive-net
    sysctls:
      net.ipv4.tcp_keepalive_time: 10
      net.ipv4.tcp_keepalive_intvl: 5
      net.ipv4.tcp_keepalive_probes: 3

networks:
  keepalive-net:
