apiVersion: apps/v1
kind: Deployment
metadata:
  name: ansible-targets
  labels:
    app: test
spec:
  replicas: 10
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: python-node
        image: python:3.12-slim  # Python is ALREADY here
        command: ["/bin/sh", "-c", "while true; do sleep 3600; done"]
